/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.Vistas;



import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.example.Gestores.GestorRevision;
import org.example.Modelos.DefectoVisual;
import org.example.Modelos.Empleado;
import org.example.Modelos.Medicion;
import org.example.Modelos.Revision;


/**
 *
 * @author oroca
 */
public class FinalizarRevision extends javax.swing.JFrame {
    private Runnable volverCallBack;
    private Revision revision;
    private Empleado supervisor;
    private String resultado;
    private LocalDateTime fechaVencimiento;
    private GestorRevision gestorRevision;
    private DefaultTableModel datosMediciones;
    private DefaultTableModel datosDefectosVisuales;
    
    
    public FinalizarRevision(GestorRevision gestorRevision) {
        this.gestorRevision = gestorRevision;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoRegistrarDefectos = new javax.swing.JLabel();
        textoIngresoPatente = new javax.swing.JLabel();
        campoIngresoPatente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panelDefectos = new javax.swing.JPanel();
        textoVehiculo = new javax.swing.JLabel();
        campoVehiculo = new javax.swing.JTextField();
        textoCliente = new javax.swing.JLabel();
        campoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatosMedicion = new javax.swing.JTable();
        textoResMedicion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDefectosVisuales = new javax.swing.JTable();
        textoResDefectos = new javax.swing.JLabel();
        btnValidarResultado = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panelFinal = new javax.swing.JPanel();
        textoFechaVto = new javax.swing.JLabel();
        textoResultadoFinal = new javax.swing.JLabel();
        campoFechaVto = new javax.swing.JTextField();
        campoResultadoFinal = new javax.swing.JTextField();
        btnFinalizarRevision = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Applus VTV - Finalizar Revision");

        textoRegistrarDefectos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        textoRegistrarDefectos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoRegistrarDefectos.setText("Finalizar revision");

        textoIngresoPatente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoIngresoPatente.setText("Ingrese la patente del vehiculo");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        panelDefectos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoVehiculo.setText("Vehiculo");

        campoVehiculo.setEditable(false);

        textoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCliente.setText("Cliente");

        campoCliente.setEditable(false);

        datosMediciones = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"Seccion", "Valor Tomado", "Valor Referencia", "Resultado"} // Column names
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tablaDatosMedicion.setModel(datosMediciones);

        tablaDatosMedicion.setAutoCreateRowSorter(true);

        tablaDatosMedicion.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

        // Set specific column widths
        javax.swing.table.TableColumnModel columnModel = tablaDatosMedicion.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(150);
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(100);
        tablaDatosMedicion.setModel(datosMediciones);
        jScrollPane1.setViewportView(tablaDatosMedicion);

        textoResMedicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoResMedicion.setText("Resultados Medicion");

        datosDefectosVisuales = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"Defecto encontrado", "Gravedad"} // Column names
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tablaDefectosVisuales.setModel(datosDefectosVisuales);

        tablaDefectosVisuales.setAutoCreateRowSorter(true);

        tablaDefectosVisuales.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

        // Set specific column widths
        javax.swing.table.TableColumnModel columnModel2 = tablaDefectosVisuales.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(300);
        columnModel.getColumn(1).setPreferredWidth(100);
        tablaDefectosVisuales.setModel(datosDefectosVisuales);
        jScrollPane2.setViewportView(tablaDefectosVisuales);

        textoResDefectos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoResDefectos.setText("Defectos Visuales");

        btnValidarResultado.setText("Validar Resultados");
        btnValidarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDefectosLayout = new javax.swing.GroupLayout(panelDefectos);
        panelDefectos.setLayout(panelDefectosLayout);
        panelDefectosLayout.setHorizontalGroup(
            panelDefectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDefectosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelDefectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(textoResMedicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(panelDefectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(textoResDefectos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
            .addGroup(panelDefectosLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panelDefectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDefectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
            .addGroup(panelDefectosLayout.createSequentialGroup()
                .addGap(497, 497, 497)
                .addComponent(btnValidarResultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDefectosLayout.setVerticalGroup(
            panelDefectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDefectosLayout.createSequentialGroup()
                .addGroup(panelDefectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoVehiculo)
                    .addComponent(textoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDefectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(panelDefectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoResMedicion)
                    .addComponent(textoResDefectos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDefectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnValidarResultado)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        panelFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoFechaVto.setText("Fecha vencimiento");

        textoResultadoFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoResultadoFinal.setText("Resultado Final");

        campoFechaVto.setEditable(false);

        campoResultadoFinal.setEditable(false);

        btnFinalizarRevision.setText("Finalizar Revision");
        btnFinalizarRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarRevisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFinalLayout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoFechaVto)
                            .addComponent(textoFechaVto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(232, 232, 232)
                        .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoResultadoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoResultadoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFinalLayout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addComponent(btnFinalizarRevision)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFechaVto)
                    .addComponent(textoResultadoFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFechaVto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoResultadoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnFinalizarRevision)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelDefectos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoRegistrarDefectos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoIngresoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addComponent(textoIngresoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(textoRegistrarDefectos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoIngresoPatente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIngresoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDefectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        this.revision = gestorRevision.buscarRevisionActivaPorPatente(this.campoIngresoPatente.getText());
        
        if (this.revision != null){
            this.campoVehiculo.setText(revision.getVehiculo().toString());
            this.campoCliente.setText(revision.getVehiculo().getDueno().getNombre() + " " + revision.getVehiculo().getDueno().getApellido());
            
            setDatosMediciones();
            setDatosDefectos();
            
            this.panelDefectos.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo encontrar la revision, revise el numero de patente e intente nuevamente",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if(this.volverCallBack!=null){
            this.volverCallBack.run();
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnValidarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarResultadoActionPerformed
        // TODO add your handling code here:
        fechaVencimiento = null;
        
        resultado = revision.calcularResultado();
        
        campoResultadoFinal.setText(resultado);
        
        switch (resultado) {
            case "Aprobado" -> fechaVencimiento = LocalDateTime.now().plusYears(1);
            
            case "Condicional" -> fechaVencimiento = LocalDateTime.now().plusMonths(2);
            
            case "Rechazada" -> fechaVencimiento = LocalDateTime.now().plusDays(1);             
        }
        
        campoFechaVto.setText(fechaVencimiento.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        
        panelFinal.setVisible(true);
    }//GEN-LAST:event_btnValidarResultadoActionPerformed

    private void btnFinalizarRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarRevisionActionPerformed
        // TODO add your handling code here:
        revision.registrarFinalizacionDeRevision(fechaVencimiento, resultado,supervisor);
        
        JOptionPane.showMessageDialog(
                    this,
                    "Revision finalizada Correctamente!",
                    "Revision finalizada",
                    JOptionPane.INFORMATION_MESSAGE
            );
        
        if(volverCallBack!=null){
            volverCallBack.run();
            this.dispose();
        }
    }//GEN-LAST:event_btnFinalizarRevisionActionPerformed

    
    public void mostrarPantalla(Empleado supervisor){
        this.supervisor = supervisor;
        
        setCamposVacios();
       
        this.panelDefectos.setVisible(false);
        this.panelFinal.setVisible(false);
        
        this.setVisible(true);
    }
    
    public void setOnVolverCallback(Runnable callback) {
        this.volverCallBack = callback;
    }
    
  
    
    private void setDatosMediciones(){
        datosMediciones.setRowCount(0);
        
        for(Medicion medicion : revision.getListaMediciones()){
            datosMediciones.addRow(new Object[]{
                medicion.getSeccion(),
                medicion.getMedida(),
                medicion.getValorReferencia(),
                medicion.getResultadoSeccion()
            });
        }
    }
    
    private void setDatosDefectos(){
        datosDefectosVisuales.setRowCount(0);
        
        for(DefectoVisual defectoVisual : revision.getListaDefectosVisuales()){
            datosDefectosVisuales.addRow(new Object[]{
                defectoVisual.getDescrpcion(),
                defectoVisual.getCalificacionDefecto()
            });
        }
    }


    private void setCamposVacios(){
        this.campoIngresoPatente.setText("");
        this.campoVehiculo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizarRevision;
    private javax.swing.JButton btnValidarResultado;
    private javax.swing.JTextField campoCliente;
    private javax.swing.JTextField campoFechaVto;
    private javax.swing.JTextField campoIngresoPatente;
    private javax.swing.JTextField campoResultadoFinal;
    private javax.swing.JTextField campoVehiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelDefectos;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JTable tablaDatosMedicion;
    private javax.swing.JTable tablaDefectosVisuales;
    private javax.swing.JLabel textoCliente;
    private javax.swing.JLabel textoFechaVto;
    private javax.swing.JLabel textoIngresoPatente;
    private javax.swing.JLabel textoRegistrarDefectos;
    private javax.swing.JLabel textoResDefectos;
    private javax.swing.JLabel textoResMedicion;
    private javax.swing.JLabel textoResultadoFinal;
    private javax.swing.JLabel textoVehiculo;
    // End of variables declaration//GEN-END:variables
}
