/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.Vistas;

import javax.swing.JOptionPane;
import org.example.Gestores.GestorEmpleado;
import org.example.Modelos.Empleado;

/**
 *
 * @author oroca
 */
public class IniciarSesion extends javax.swing.JFrame {
    private boolean presionado;
    
    public IniciarSesion() {
        initComponents();
        this.presionado = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoApplus = new javax.swing.JLabel();
        textoIniciarSesion = new javax.swing.JLabel();
        textoIngreseEmail = new javax.swing.JLabel();
        campoEntradaMail = new javax.swing.JTextField();
        textoIngreseLegajo = new javax.swing.JLabel();
        campoEntradaLegajo = new javax.swing.JTextField();
        botonIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Applus VTV - Iniciar Sesion");

        logoApplus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoApplus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesVistas/LogoApplus.png"))); // NOI18N

        textoIniciarSesion.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        textoIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoIniciarSesion.setText("Iniciar Sesión");

        textoIngreseEmail.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        textoIngreseEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoIngreseEmail.setText("Ingrese su Email");

        campoEntradaMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEntradaMailActionPerformed(evt);
            }
        });

        textoIngreseLegajo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        textoIngreseLegajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoIngreseLegajo.setText("Ingrese su legajo");

        botonIniciarSesion.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        botonIniciarSesion.setText("Iniciar Sesión");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoApplus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoIniciarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textoIngreseEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoIngreseLegajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(campoEntradaLegajo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(campoEntradaMail, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(logoApplus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoIniciarSesion)
                .addGap(18, 18, 18)
                .addComponent(textoIngreseEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEntradaMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textoIngreseLegajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEntradaLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonIniciarSesion)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        //Al presionar el boton de iniciar sesion se setea la variable en true y se desactiva la espera
        presionado = true;
        
        synchronized (this) {
            notify();
        }
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    private void campoEntradaMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEntradaMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEntradaMailActionPerformed


    
    public Empleado iniciarSesion(GestorEmpleado gestorEmpleado){
        //Se inicia una espera hasta que el usuario ingrese los datos requeridos y pulse el boton
        synchronized (this) {
            while(!presionado){
                try{
                    wait();
                }catch (InterruptedException e) {
                    System.err.print(e);
                }
            }  
        }
        
        //Se llama al metodo que busca al empleado si el email y legajo coinciden
        Empleado empleado = gestorEmpleado.buscarEmpleadoPorEmailYLegajo(campoEntradaMail.getText(), campoEntradaLegajo.getText());
        
        //Se coloca la variable presionado nuevamente en false y se restablecen los campos de ingreso
        presionado = false;
        campoEntradaMail.setText("");
        campoEntradaLegajo.setText("");
        
        //Si se encuentra al empleado se retorna el valor a la clase Main
        if (empleado!=null){
            return empleado;
            
        //Si no se encunetra se muestra un mensaje de error y se devuelve null
        }else{
            JOptionPane.showMessageDialog(
                    null,
                    "No se pudo iniciar sesion, mail o legajo incorrecto, revisalo e intenta de nuevo",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            
            return null;
        }       
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JTextField campoEntradaLegajo;
    private javax.swing.JTextField campoEntradaMail;
    private javax.swing.JLabel logoApplus;
    private javax.swing.JLabel textoIngreseEmail;
    private javax.swing.JLabel textoIngreseLegajo;
    private javax.swing.JLabel textoIniciarSesion;
    // End of variables declaration//GEN-END:variables
}
