/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.Vistas;

import javax.swing.JOptionPane;
import org.example.Gestores.GestorCliente;

/**
 *
 * @author oroca
 */
public class RegistrarCliente extends javax.swing.JFrame {
    private Runnable volverCallBack;
    private GestorCliente gestorCliente;

    public RegistrarCliente(GestorCliente gestorCliente) {
        this.gestorCliente = gestorCliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoRegistrarNuevoCliente = new javax.swing.JLabel();
        textoCompleteCampos = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        textoApellido = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        textoNroDni = new javax.swing.JLabel();
        campoNroDni = new javax.swing.JTextField();
        textoTipoDni = new javax.swing.JLabel();
        selectorTipoDni = new javax.swing.JComboBox<>();
        textoNroTel = new javax.swing.JLabel();
        campoNroTel = new javax.swing.JTextField();
        textoEmail = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        textoLocalidad = new javax.swing.JLabel();
        campoLocalidad = new javax.swing.JTextField();
        textoDireccion = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Applus VTV - Registrar Cliente");

        textoRegistrarNuevoCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textoRegistrarNuevoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoRegistrarNuevoCliente.setText("Registrar nuevo cliente");

        textoCompleteCampos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCompleteCampos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCompleteCampos.setText("Complete todos los campos debidamente");

        textoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoNombre.setText("Nombre/s");

        textoApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoApellido.setText("Apellido/s");

        textoNroDni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoNroDni.setText("Numero Documento");

        textoTipoDni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTipoDni.setText("Tipo Documento");

        selectorTipoDni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "CUIL", "CUIT", "DNI Extranjero", "Pasaporte" }));

        textoNroTel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoNroTel.setText("Numero de Telefono");

        textoEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoEmail.setText("Email");

        textoLocalidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoLocalidad.setText("Localidad");

        textoDireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoDireccion.setText("Direccion");

        botonRegistrar.setText("Registrar Cliente");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar Registro");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textoRegistrarNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textoCompleteCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNroDni, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoNroDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoNroTel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoNroTel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonRegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoApellido)
                            .addComponent(textoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoTipoDni, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(selectorTipoDni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoEmail)
                            .addComponent(textoLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoLocalidad)
                            .addComponent(textoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(0, 243, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(textoRegistrarNuevoCliente)
                .addGap(34, 34, 34)
                .addComponent(textoCompleteCampos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombre)
                    .addComponent(textoApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoNroDni)
                    .addComponent(textoTipoDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectorTipoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNroDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoDireccion)
                    .addComponent(textoLocalidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoNroTel)
                    .addComponent(textoEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNroTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonRegistrar))
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        if(volverCallBack!=null){
            volverCallBack.run();
            setCamposVacios();
            this.dispose();
        }
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:
        gestorCliente.registrarCliente(campoNombre.getText(),
                campoApellido.getText(),
                campoDireccion.getText(),
                campoLocalidad.getText(),
                campoNroTel.getText(),
                campoEmail.getText(),
                selectorTipoDni.getSelectedItem().toString(),
                campoNroDni.getText()
        );
        
        JOptionPane.showMessageDialog(
                    this,
                    "Cliente Registrado Correctamente!",
                    "Cliente Registrado",
                    JOptionPane.INFORMATION_MESSAGE
            );
        
        if(volverCallBack!=null){
            volverCallBack.run();
            
            setCamposVacios();
            this.dispose();
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed


    
    public void mostrarPantalla(){
        this.setVisible(true);
    }
    
    
    public void setOnVolverCallback(Runnable callback) {
        this.volverCallBack = callback;
    }
    
    private void setCamposVacios(){
        campoNombre.setText("");
        campoApellido.setText("");
        campoNroDni.setText("");
        campoDireccion.setText("");
        campoLocalidad.setText("");
        campoNroTel.setText("");
        campoEmail.setText("");     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoLocalidad;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNroDni;
    private javax.swing.JTextField campoNroTel;
    private javax.swing.JComboBox<String> selectorTipoDni;
    private javax.swing.JLabel textoApellido;
    private javax.swing.JLabel textoCompleteCampos;
    private javax.swing.JLabel textoDireccion;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoLocalidad;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoNroDni;
    private javax.swing.JLabel textoNroTel;
    private javax.swing.JLabel textoRegistrarNuevoCliente;
    private javax.swing.JLabel textoTipoDni;
    // End of variables declaration//GEN-END:variables
}
