/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.Vistas;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.example.Gestores.GestorCliente;
import org.example.Gestores.GestorRevision;
import org.example.Gestores.GestorVehiculo;
import org.example.Modelos.Cliente;
import org.example.Modelos.Vehiculo;

/**
 *
 * @author oroca
 */
public class RegistrarRevision extends javax.swing.JFrame {
    private Runnable volverCallBack;
    private DefaultListModel<Vehiculo> datosVehiculosCliente;
    private Cliente cliente;
    private GestorCliente gestorCliente;
    private GestorVehiculo gestorVehiculo;
    private GestorRevision gestorRevision;
    private RegistrarCliente pantallaRegistrarCliente;
    private RegistrarVehiculo pantallaRegistrarVehiculo;
    
    public RegistrarRevision(GestorCliente gestorCliente, GestorVehiculo gestorVehiculo, GestorRevision gestorRevision, RegistrarCliente pantallaRegistrarCliente, RegistrarVehiculo pantallaRegistrarVehiculo) {
        this.gestorCliente = gestorCliente;
        this.gestorVehiculo = gestorVehiculo;
        this.gestorRevision = gestorRevision;
        this.pantallaRegistrarCliente = pantallaRegistrarCliente;
        this.pantallaRegistrarVehiculo = pantallaRegistrarVehiculo;
        this.datosVehiculosCliente = new DefaultListModel<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoRegistrarRevision = new javax.swing.JLabel();
        textoIngreseDoc = new javax.swing.JLabel();
        campoNroDni = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        panelVehiculo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaVehiculos = new javax.swing.JList<>();
        btnRegistrarVehiculo = new javax.swing.JButton();
        textoSeleccionVehiculo = new javax.swing.JLabel();
        textoCliente = new javax.swing.JLabel();
        campoCliente = new javax.swing.JTextField();
        btnRegistrarCliente = new javax.swing.JButton();
        panelFinal = new javax.swing.JPanel();
        textoFechaRegistro = new javax.swing.JLabel();
        textoCosto = new javax.swing.JLabel();
        campoFecha = new javax.swing.JTextField();
        campoCosto = new javax.swing.JTextField();
        btnRegistrarRevision = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Applus VTV - Registrar Revision");

        textoRegistrarRevision.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        textoRegistrarRevision.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoRegistrarRevision.setText("Registrar revisión");

        textoIngreseDoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoIngreseDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoIngreseDoc.setText("Ingrese el documento del cliente");

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        listaVehiculos.setModel(datosVehiculosCliente);
        listaVehiculos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaVehiculos);

        btnRegistrarVehiculo.setText("Registrar Nuevo Vehiculo");
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });

        textoSeleccionVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoSeleccionVehiculo.setText("Seleccione uno de los vehiculos del cliente: ");

        textoCliente.setText("Cliente:");

        javax.swing.GroupLayout panelVehiculoLayout = new javax.swing.GroupLayout(panelVehiculo);
        panelVehiculo.setLayout(panelVehiculoLayout);
        panelVehiculoLayout.setHorizontalGroup(
            panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVehiculoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(textoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(textoSeleccionVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelVehiculoLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnRegistrarVehiculo)))
                .addGap(339, 339, 339))
        );
        panelVehiculoLayout.setVerticalGroup(
            panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(textoSeleccionVehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoCliente)
                        .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarVehiculo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnRegistrarCliente.setText("Registrar");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        textoFechaRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoFechaRegistro.setText("Fecha de Registro");

        textoCosto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCosto.setText("Costo");

        btnRegistrarRevision.setText("Registrar Revisión");
        btnRegistrarRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRevisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinalLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoFecha)
                    .addComponent(textoFechaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCosto, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(textoCosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(319, 319, 319))
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addGap(427, 427, 427)
                .addComponent(btnRegistrarRevision)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFechaRegistro)
                    .addComponent(textoCosto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnRegistrarRevision)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(campoNroDni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelVehiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoRegistrarRevision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoIngreseDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(textoRegistrarRevision)
                .addGap(18, 18, 18)
                .addComponent(textoIngreseDoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNroDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(btnRegistrarCliente))
                .addGap(38, 38, 38)
                .addComponent(panelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if(volverCallBack!=null){
            volverCallBack.run();
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        cliente = gestorCliente.buscarClientePorDni(campoNroDni.getText());
        
        if (cliente !=null){
            campoCliente.setText(cliente.getNombre() + " " + cliente.getApellido());
            setListaVehiculosCliente();
            this.panelVehiculo.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo encontrar el cliente, revise el numero de documento e intente nuevamente",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        pantallaRegistrarCliente.mostrarPantalla();
        
        pantallaRegistrarCliente.setOnVolverCallback(() -> {
            this.setVisible(true); 
        });
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        pantallaRegistrarVehiculo.mostrarPantalla();
        
        pantallaRegistrarVehiculo.setOnVolverCallback(() -> {
            setListaVehiculosCliente();
            this.setVisible(true);
           
        });
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed

    private void listaVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaVehiculosMouseClicked
        // TODO add your handling code here:
        
        campoCosto.setText("$" + listaVehiculos.getSelectedValue().getTipoVehiculo().getPrecioRevision());
        campoFecha.setText(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        
        panelFinal.setVisible(true);
    }//GEN-LAST:event_listaVehiculosMouseClicked

    private void btnRegistrarRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRevisionActionPerformed
        // TODO add your handling code here:
        gestorRevision.registrarRevision(listaVehiculos.getSelectedValue(), LocalDateTime.now());
        
         JOptionPane.showMessageDialog(
                    null,
                    "Revision Registrada Correctamente!",
                    "Revision Registrada",
                    JOptionPane.INFORMATION_MESSAGE
            );
        
        if(volverCallBack!=null){
            volverCallBack.run();
            this.dispose();
        }
    }//GEN-LAST:event_btnRegistrarRevisionActionPerformed


    
    public void mostrarPantalla(){
        setCamposVacios();
        
        panelVehiculo.setVisible(false);
        panelFinal.setVisible(false);
        
        this.setVisible(true);
    }
    
    public void setOnVolverCallback(Runnable callback) {
        this.volverCallBack = callback;
    }
    
    private void setListaVehiculosCliente(){
        datosVehiculosCliente.setSize(0);
        
        for (Vehiculo vehiculo : gestorVehiculo.getListaVehiculos()){
            if(vehiculo.getDueno() == this.cliente){
                datosVehiculosCliente.addElement(vehiculo);
            }
        }          
    }
    
    private void setCamposVacios(){
        campoNroDni.setText("");
        campoCliente.setText("");
        campoFecha.setText("");
        campoCosto.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegistrarRevision;
    private javax.swing.JButton btnRegistrarVehiculo;
    private javax.swing.JTextField campoCliente;
    private javax.swing.JTextField campoCosto;
    private javax.swing.JTextField campoFecha;
    private javax.swing.JTextField campoNroDni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Vehiculo> listaVehiculos;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelVehiculo;
    private javax.swing.JLabel textoCliente;
    private javax.swing.JLabel textoCosto;
    private javax.swing.JLabel textoFechaRegistro;
    private javax.swing.JLabel textoIngreseDoc;
    private javax.swing.JLabel textoRegistrarRevision;
    private javax.swing.JLabel textoSeleccionVehiculo;
    // End of variables declaration//GEN-END:variables
}
