/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.Vistas;

import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import org.example.Gestores.GestorRevision;
import org.example.Modelos.Revision;

/**
 *
 * @author oroca
 */
public class RegistrarCancelacion extends javax.swing.JFrame {
    private Runnable volverCallBack;
    private Revision revision;
    private GestorRevision gestorRevision;
    
    public RegistrarCancelacion(GestorRevision gestorRevision) {
        this.gestorRevision = gestorRevision;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoRegistrarCancleacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoIngresoPatente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panelDatosRevision = new javax.swing.JPanel();
        textoVehiculo = new javax.swing.JLabel();
        campoVehiculo = new javax.swing.JTextField();
        campoCliente = new javax.swing.JTextField();
        textoCliente = new javax.swing.JLabel();
        textoFechaHora = new javax.swing.JLabel();
        campoFechaHora = new javax.swing.JTextField();
        btnRegCancelacion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Applus VTV - Cancelar Revision");

        textoRegistrarCancleacion.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        textoRegistrarCancleacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoRegistrarCancleacion.setText("Cancelar Revision");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese la patente del vehiculo");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        panelDatosRevision.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoVehiculo.setText("Vehiculo");

        campoVehiculo.setEditable(false);

        campoCliente.setEditable(false);

        textoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCliente.setText("Cliente");

        textoFechaHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoFechaHora.setText("Fecha y hora de inicio");

        campoFechaHora.setEditable(false);

        btnRegCancelacion.setText("Registrar Cancelación");
        btnRegCancelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegCancelacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosRevisionLayout = new javax.swing.GroupLayout(panelDatosRevision);
        panelDatosRevision.setLayout(panelDatosRevisionLayout);
        panelDatosRevisionLayout.setHorizontalGroup(
            panelDatosRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosRevisionLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(panelDatosRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textoFechaHora, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(campoFechaHora, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoVehiculo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoVehiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(panelDatosRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(textoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(panelDatosRevisionLayout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(btnRegCancelacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosRevisionLayout.setVerticalGroup(
            panelDatosRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosRevisionLayout.createSequentialGroup()
                .addGroup(panelDatosRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosRevisionLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(textoVehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(textoFechaHora))
                    .addGroup(panelDatosRevisionLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(textoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btnRegCancelacion)
                .addGap(29, 29, 29))
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoIngresoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoRegistrarCancleacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatosRevision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(textoRegistrarCancleacion)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIngresoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(panelDatosRevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if(this.volverCallBack!=null){
            this.volverCallBack.run();
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        this.revision = gestorRevision.buscarRevisionActivaPorPatente(this.campoIngresoPatente.getText());
        
        if (this.revision != null){
            this.campoVehiculo.setText(revision.getVehiculo().toString());
            this.campoCliente.setText(this.revision.getVehiculo().getDueno().getNombre() + " " + this.revision.getVehiculo().getDueno().getApellido());
            this.campoFechaHora.setText(revision.getFechaRealizacion().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));
            
            this.panelDatosRevision.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo encontrar la revision, revise el numero de patente e intente nuevamente",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegCancelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegCancelacionActionPerformed
        // TODO add your handling code here:
        gestorRevision.registrarCancelacion(revision);
        
        JOptionPane.showMessageDialog(
                    this,
                    "Revision cancelada correctamente",
                    "Revision cancelada",
                    JOptionPane.INFORMATION_MESSAGE
            );
        
        if(this.volverCallBack!=null){
            this.volverCallBack.run();
            this.dispose();
        }
    }//GEN-LAST:event_btnRegCancelacionActionPerformed

    
    public void mostrarPantalla(){
        setCamposVacios();
        this.panelDatosRevision.setVisible(false);
        
        this.setVisible(true);
    }
    
    public void setOnVolverCallback(Runnable callback) {
        this.volverCallBack = callback;
    }
    
    private void setCamposVacios(){
        this.campoIngresoPatente.setText("");
        this.campoVehiculo.setText("");
        this.campoCliente.setText("");
        this.campoFechaHora.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegCancelacion;
    private javax.swing.JTextField campoCliente;
    private javax.swing.JTextField campoFechaHora;
    private javax.swing.JTextField campoIngresoPatente;
    private javax.swing.JTextField campoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelDatosRevision;
    private javax.swing.JLabel textoCliente;
    private javax.swing.JLabel textoFechaHora;
    private javax.swing.JLabel textoRegistrarCancleacion;
    private javax.swing.JLabel textoVehiculo;
    // End of variables declaration//GEN-END:variables
}
