/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.Vistas;

import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.example.Gestores.GestorRevision;
import org.example.Gestores.GestorSeccion;
import org.example.Modelos.Empleado;
import org.example.Modelos.Revision;
import org.example.Modelos.Seccion;

/**
 *
 * @author oroca
 */
public class RegistrarMedicion extends javax.swing.JFrame {
    private Runnable volverCallBack;
    private Revision revision;
    private Empleado inspector;
    private DefaultComboBoxModel<Seccion> listadoSecciones;
    private GestorRevision gestorRevision;
    private GestorSeccion gestorSeccion;
    
    
    public RegistrarMedicion(GestorRevision gestorRevision, GestorSeccion gestorSeccion) {
        this.gestorRevision = gestorRevision;
        this.gestorSeccion = gestorSeccion;
        this.listadoSecciones = new DefaultComboBoxModel<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoRegistrarMedicion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoIngresoPatente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panelDatosMedicion = new javax.swing.JPanel();
        textoVehiculo = new javax.swing.JLabel();
        campoVehiculo = new javax.swing.JTextField();
        textoSeccionActual = new javax.swing.JLabel();
        selectorSeccion = new javax.swing.JComboBox<>();
        textoValorMedida = new javax.swing.JLabel();
        textoValorReferencia = new javax.swing.JLabel();
        campoIngresoMedida = new javax.swing.JTextField();
        campoValorReferencia = new javax.swing.JTextField();
        btnRegistrarRevision = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Applus VTV - Registrar Medicion");

        textoRegistrarMedicion.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        textoRegistrarMedicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoRegistrarMedicion.setText("Registrar Medicion");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese la patente del vehiculo");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        textoVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoVehiculo.setText("Vehiculo");

        campoVehiculo.setEditable(false);

        textoSeccionActual.setText("Seleccione la seccion actual");

        selectorSeccion.setModel(setListadoSecciones());

        textoValorMedida.setText("Ingrese el valor de la medida");

        textoValorReferencia.setText("Ingrese el valor de referencia");

        btnRegistrarRevision.setText("Registrar Medicion");
        btnRegistrarRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRevisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosMedicionLayout = new javax.swing.GroupLayout(panelDatosMedicion);
        panelDatosMedicion.setLayout(panelDatosMedicionLayout);
        panelDatosMedicionLayout.setHorizontalGroup(
            panelDatosMedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosMedicionLayout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addGroup(panelDatosMedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoValorReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoIngresoMedida)
                    .addComponent(textoSeccionActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectorSeccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoValorMedida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoValorReferencia)
                    .addComponent(btnRegistrarRevision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelDatosMedicionLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(panelDatosMedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        panelDatosMedicionLayout.setVerticalGroup(
            panelDatosMedicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosMedicionLayout.createSequentialGroup()
                .addComponent(textoVehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(textoSeccionActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectorSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoValorMedida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoIngresoMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoValorReferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoValorReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarRevision)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoIngresoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoRegistrarMedicion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelDatosMedicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCancelar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(textoRegistrarMedicion)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIngresoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(panelDatosMedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if(this.volverCallBack!=null){
            this.volverCallBack.run();
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        this.revision = gestorRevision.buscarRevisionActivaPorPatente(this.campoIngresoPatente.getText());
        
        if (this.revision != null){
            this.campoVehiculo.setText(revision.getVehiculo().toString());
            
            this.panelDatosMedicion.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo encontrar la revision, revise el numero de patente e intente nuevamente",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegistrarRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRevisionActionPerformed
        // TODO add your handling code here:
        this.revision.registrarMedicion(
                (Seccion) selectorSeccion.getSelectedItem(), 
                Integer.parseInt(campoIngresoMedida.getText()), 
                Integer.parseInt(campoValorReferencia.getText()), 
                inspector
        );
        
        JOptionPane.showMessageDialog(
                    null,
                    "Medicion Registrada Correctamente!",
                    "Medicion Registrada",
                    JOptionPane.INFORMATION_MESSAGE
            );
        
        if(volverCallBack!=null){
            volverCallBack.run();
            this.dispose();
        }
    }//GEN-LAST:event_btnRegistrarRevisionActionPerformed

    
    public void mostrarPantalla(Empleado inspector){
        this.inspector = inspector;
        
        setCamposVacios();
        this.panelDatosMedicion.setVisible(false);
        
        this.setVisible(true);
    }
    
    public void setOnVolverCallback(Runnable callback) {
        this.volverCallBack = callback;
    }
    
    private DefaultComboBoxModel<Seccion> setListadoSecciones(){
        listadoSecciones.removeAllElements();
        
        for(Seccion seccion : gestorSeccion.getListaSecciones()){
            listadoSecciones.addElement(seccion);
        }
        
        return listadoSecciones;
    }
    

    
    private void setCamposVacios(){
        this.campoIngresoPatente.setText("");
        this.campoVehiculo.setText("");
        this.campoIngresoMedida.setText("");
        this.campoValorReferencia.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrarRevision;
    private javax.swing.JTextField campoIngresoMedida;
    private javax.swing.JTextField campoIngresoPatente;
    private javax.swing.JTextField campoValorReferencia;
    private javax.swing.JTextField campoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelDatosMedicion;
    private javax.swing.JComboBox<Seccion> selectorSeccion;
    private javax.swing.JLabel textoRegistrarMedicion;
    private javax.swing.JLabel textoSeccionActual;
    private javax.swing.JLabel textoValorMedida;
    private javax.swing.JLabel textoValorReferencia;
    private javax.swing.JLabel textoVehiculo;
    // End of variables declaration//GEN-END:variables
}
