/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.Vistas;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.example.Gestores.GestorCliente;
import org.example.Gestores.GestorVehiculo;
import org.example.Modelos.Cliente;
import org.example.Modelos.TipoVehiculo;

/**
 *
 * @author oroca
 */
public class RegistrarVehiculo extends javax.swing.JFrame {
    private Runnable volverCallBack;
    private DefaultComboBoxModel<TipoVehiculo> listadoTiposVehiculo;
    private GestorCliente gestorCliente;
    private GestorVehiculo gestorVehiculo;
    private Cliente cliente;

    public RegistrarVehiculo(GestorCliente gestorCliente , GestorVehiculo gestorVehiculo) {
        this.gestorCliente = gestorCliente;
        this.gestorVehiculo = gestorVehiculo;
        this.listadoTiposVehiculo = new DefaultComboBoxModel<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoRegistrarNuevoCliente = new javax.swing.JLabel();
        textoCompleteCampos = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        textoNroDocCliente = new javax.swing.JLabel();
        campoIngresoDni = new javax.swing.JTextField();
        panelDatosVehiculo = new javax.swing.JPanel();
        textoCliente = new javax.swing.JLabel();
        campoMuestraCliente = new javax.swing.JTextField();
        textoPatente = new javax.swing.JLabel();
        textoMarca = new javax.swing.JLabel();
        textoModelo = new javax.swing.JLabel();
        textoTipoVehiculo = new javax.swing.JLabel();
        textoAnoFabricacion = new javax.swing.JLabel();
        selectorTipoVehiculo = new javax.swing.JComboBox<>();
        campoPatente = new javax.swing.JTextField();
        campoModelo = new javax.swing.JTextField();
        campoMarca = new javax.swing.JTextField();
        campoAnoFabricacion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Applus VTV - Registrar Vehiculo");

        textoRegistrarNuevoCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textoRegistrarNuevoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoRegistrarNuevoCliente.setText("Registrar nuevo vehiculo");

        textoCompleteCampos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCompleteCampos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCompleteCampos.setText("Complete todos los campos debidamente");

        botonCancelar.setText("Cancelar Registro");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        textoNroDocCliente.setText("Ingrese el Numero de documento del cliente");

        textoCliente.setText("Cliente:");

        campoMuestraCliente.setEditable(false);

        textoPatente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPatente.setText("Patente");

        textoMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoMarca.setText("Marca");

        textoModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoModelo.setText("Modelo");

        textoTipoVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTipoVehiculo.setText("Tipo de Vehiculo");

        textoAnoFabricacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoAnoFabricacion.setText("Año Fabricacion");

        selectorTipoVehiculo.setModel(setListadoTiposVehiculo());

        btnRegistrar.setText("Registrar Vehiculo");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosVehiculoLayout = new javax.swing.GroupLayout(panelDatosVehiculo);
        panelDatosVehiculo.setLayout(panelDatosVehiculoLayout);
        panelDatosVehiculoLayout.setHorizontalGroup(
            panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosVehiculoLayout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosVehiculoLayout.createSequentialGroup()
                        .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosVehiculoLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(textoCliente))
                            .addGroup(panelDatosVehiculoLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(campoMuestraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosVehiculoLayout.createSequentialGroup()
                                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textoPatente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(88, 88, 88)
                                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoTipoVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(campoMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textoMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selectorTipoVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(333, 333, 333))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosVehiculoLayout.createSequentialGroup()
                            .addComponent(campoAnoFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosVehiculoLayout.createSequentialGroup()
                            .addComponent(textoAnoFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(435, 435, 435)))))
        );
        panelDatosVehiculoLayout.setVerticalGroup(
            panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMuestraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPatente)
                    .addComponent(textoTipoVehiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoModelo)
                    .addComponent(textoMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(textoAnoFabricacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAnoFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoIngresoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarCliente))
                    .addComponent(textoNroDocCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoRegistrarNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoCompleteCampos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatosVehiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(textoRegistrarNuevoCliente)
                .addGap(34, 34, 34)
                .addComponent(textoCompleteCampos)
                .addGap(18, 18, 18)
                .addComponent(textoNroDocCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIngresoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addGap(23, 23, 23)
                .addComponent(panelDatosVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(botonCancelar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        if(volverCallBack!=null){
            volverCallBack.run();
            setCamposVacios();
            this.dispose();
        }
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        cliente = gestorCliente.buscarClientePorDni(campoIngresoDni.getText());
        
        if (cliente !=null){
            campoMuestraCliente.setText(cliente.getNombre() + " " + cliente.getApellido());
            this.panelDatosVehiculo.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(
                    null,
                    "No se pudo encontrar el cliente, revise el numero de documento e intente nuevamente",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        gestorVehiculo.registrarVehiculo(this.cliente,
                campoMarca.getText(),
                campoModelo.getText(), 
                (TipoVehiculo) selectorTipoVehiculo.getSelectedItem(),
                campoAnoFabricacion.getText(),
                campoPatente.getText()
        );
        
        JOptionPane.showMessageDialog(
                    null,
                    "Vehiculo Registrado Correctamente!",
                    "Vehiculo Registrado",
                    JOptionPane.INFORMATION_MESSAGE
            );
        
        if(volverCallBack!=null){
            volverCallBack.run();
            setCamposVacios();
            this.dispose();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed


    
    public void mostrarPantalla(){
        setListadoTiposVehiculo();
        this.panelDatosVehiculo.setVisible(false);
        setCamposVacios();
        this.setVisible(true);
    }
    
    
    public void setOnVolverCallback(Runnable callback) {
        this.volverCallBack = callback;
    }
    
    private DefaultComboBoxModel setListadoTiposVehiculo(){
        listadoTiposVehiculo.removeAllElements();
        
        for(TipoVehiculo tipoVehiculo : gestorVehiculo.getListaTipoVehiculos()){
            listadoTiposVehiculo.addElement(tipoVehiculo);
        }
        selectorTipoVehiculo.setModel(listadoTiposVehiculo);
        
        return listadoTiposVehiculo;
    }
    
    private void setCamposVacios(){
        campoIngresoDni.setText("");
        campoPatente.setText("");
        campoMarca.setText("");
        campoModelo.setText("");
        campoAnoFabricacion.setText("");
        campoMuestraCliente.setText("");   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField campoAnoFabricacion;
    private javax.swing.JTextField campoIngresoDni;
    private javax.swing.JTextField campoMarca;
    private javax.swing.JTextField campoModelo;
    private javax.swing.JTextField campoMuestraCliente;
    private javax.swing.JTextField campoPatente;
    private javax.swing.JPanel panelDatosVehiculo;
    private javax.swing.JComboBox<TipoVehiculo> selectorTipoVehiculo;
    private javax.swing.JLabel textoAnoFabricacion;
    private javax.swing.JLabel textoCliente;
    private javax.swing.JLabel textoCompleteCampos;
    private javax.swing.JLabel textoMarca;
    private javax.swing.JLabel textoModelo;
    private javax.swing.JLabel textoNroDocCliente;
    private javax.swing.JLabel textoPatente;
    private javax.swing.JLabel textoRegistrarNuevoCliente;
    private javax.swing.JLabel textoTipoVehiculo;
    // End of variables declaration//GEN-END:variables
}
